name: Update Contributors

on:
  schedule:
    - cron: '30 13 1,15 * *'
  workflow_dispatch:

jobs:
  update-contributors:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Contributors
        id: contributors
        run: |
          contributors=$(curl -s https://api.github.com/repos/JairTorres1003/JT-Workflows/contributors | jq -r '.[].login')
          echo "::set-output name=contributors::$contributors"

      - name: Update README
        run: |
          sed -i '/## Contributors/q' README.md
          echo "## Contributors" >> README.md
          for contributor in ${{ steps.contributors.outputs.contributors }}; do
            avatar_url=$(curl -s https://api.github.com/users/$contributor | jq -r '.avatar_url')
            echo "![${contributor}](${avatar_url}&s=100&border-radius=50%)" >> README.md
          done

      - name: Debug Information
        run: |
          echo "GitHub Repository: ${GITHUB_REPOSITORY}"
          echo "GitHub Token: ${GITHUB_TOKEN}"
          git status
          git remote -v

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update Contributors"
          git push https://${{ GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
