name: Update Contributors

on:
  schedule:
    - cron: '30 13 1,15 * *'
  workflow_dispatch:
  
jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Update Contributors
      run: node update-contributors.js

    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add README.md
        git commit -m "Update Contributors [skip ci]"
        git push

    - name: Update Contributors Image
      run: |
        for contributor in $(curl -s https://api.github.com/repos/tu-usuario/tu-repositorio/contributors | jq -r '.[].login'); do
          avatar_url=$(curl -s "https://api.github.com/users/$contributor" | jq -r '.avatar_url')
          wget -O "$contributor.jpg" "$avatar_url"
          convert "$contributor.jpg" -resize 100x100^ -gravity center -extent 100x100 -alpha set -background none -define png:color-type=6 "$contributor.png"
          sed -i "s|@${contributor}@|![${contributor}](${contributor}.png)|g" README.md
        done
        git add README.md
        git commit -m "Update Contributors Images [skip ci]"
        git push
